language: generic
sudo: required
services:
  - docker


before-install:
  - docker build -t hirschstevenw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hirschstevenw/react-test npm run test -- --coverage

after_success:
  - docker build -t hirschstevenw/multi-client ./client
  - docker build -t hirschstevenw/multi-nginx ./nginx
  - docker build -t hirschstevenw/multi-server ./server
  - docker build -t hirschstevenw/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push hirschstevenw/multi-client
  - docker push hirschstevenw/multi-nginx
  - docker push hirschstevenw/multi-server
  - docker push hirschstevenw/multi-worker


