language: generic
sudo: required
services:
  - docker


before-install:
  - docker build -t hirschstevenw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hirschstevenw/react-test npm run test -- --coverage

after_success:
  - docker build -t hirschstevenw/multi-client ./client
  - docker build -t hirschstevenw/multi-nginx ./nginx
  - docker build -t hirschstevenw/multi-server ./server
  - docker build -t hirschstevenw/multi-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-131383255961"
  bucket_path: "docker-react"

  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
